### ISSUE TITLE
DOWS:true and No detection

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#229] opened 2019-11-01 21:21 UTC
When the autozoom_enabled = true, then I get detection with both { DOWS: true } or { DOWS: false} options. 
However, I don't get any detection, when the camera has `autozoom_enabled = false`, and `{ DOWS: true }` .  
Shouldn't  people counting work in both cases ? 

Please see the code snippet, camera and sdk info bellow 

```
const detectorOpts = {
            DOWS: true, // DOWS: detection on with video streaming, default is false
            objectFilter: ['head', 'person']
        };
const detector = cameraManager.getDetector( detectorOpts );

await detector.init();

const c = await detector.on('DETECTIONS', _.throttle(detections => {
                const people = detections.filter(({ label }) => label === 'head');
                console.log('\tPeople count ', people.length);
            }, 5000));
```

Using 
HuddlyIQ-1.3.11-66298 
"@huddly/device-api-usb": "^0.2.12",
"@huddly/sdk": "^0.4.0",

**Comment by jontore** [comment] 2019-11-02 18:32
As long as you're streaming video and the  detector is initialised ```    detector.init();
``` it should give you detections. I'll have to try to reproduce when I'm back in the office, and get back to you.

**Comment by qmas** [comment] 2019-11-02 22:47
Yes I have the `await detector.init();`. Also video was streaming when I saw no detection as I described before

**Comment by jontore** [comment] 2019-11-04 09:41
Turns out that there is a missing bug/feature here, currently this is not possible. 

This has to do with how the overview stream is started that the detector consumes. This is either started by the detector if DOWS is false, or started by Genius Framing is DOWS is true. And in this case it is waiting for it be started. 

So the workaround here is to start Genius Framing, but turn off framing to only get detections when the main stream is used. Or DOWS false if you want detections regardless if the main stream is being used or not. 

We'll add this as an issue, and get this working a bit more intuitively. 

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', async (cameraManager) => {

        const detectorOpts = {
            DOWS: true, // DOWS: detection on with video streaming, default is false
            objectFilter: ['head']
        };
        const detector = cameraManager.getDetector( detectorOpts );
        const autozoomCtl = cameraManager.getAutozoomControl();
        await autozoomCtl.init();

        const azIsRunning = await autozoomCtl.isRunning();
        if (!azIsRunning) {
            await autozoomCtl.start();
            await autozoomCtl.uploadFramingConfig({
                shouldAutoFrame: false,
            });
        }

        detector.on('DETECTIONS', async heads => {
            console.log('\tHead count ', heads.length);
        });
        await detector.init();

    });
}

init();
```

**Comment by qmas** [comment] 2019-11-04 18:42
After workaround suggestion in previous comment, I started changing my code and narrowed down a case that needs fixing
```
if(az==false){
autozoomCtl.disable();
autozoomCtl.uploadFramingConfig({ shouldAutoFrame: false});
}
```
When the previous two lines of code execute, people counting starts working with az=false as desired. But the option DOWS:true starts acting as if it has switched to its default behavior DOWS:false: Where the people counting does not stop/pause when windows camera application minimizes (not desired). And the camera light stays on even when windows camera application is stopped or closed (also not desired). 

People count should stop/pause when windows camera app is not running or is minimized. The DOWS:true and az=true is fine and works as desired. But when DOWS:true and az=false it seems not working as described before.

**Comment by jontore** [comment] 2019-11-05 11:26
Yes you're right this was a bug in the 1.3.11 SW, this should how been resolved with the new stable SW 1.3.13. But unfortunately it looks like the workaround I suggested does work. We're looking into and hopefully we can resolve this and the underlying issue. 

I'll keep you updated.

**Comment by jontore** [comment] 2019-11-05 12:04
With 1.3.13 this should work 

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const _ = require('lodash');
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', async (cameraManager) => {

        const detectorOpts = {
            DOWS: true, // DOWS: detection on with video streaming, default is false
            objectFilter: ['head']
        };
        const detector = cameraManager.getDetector( detectorOpts );
        await detector.init();
        const autozoomCtl = cameraManager.getAutozoomControl();
        await autozoomCtl.init();
        await autozoomCtl.disable();
        detector.on('DETECTIONS', async heads => {
            console.log('\tHead count ', heads.length);
        });

        const azIsRunning = await autozoomCtl.isRunning();
        if (!azIsRunning) {
            await autozoomCtl.start();
            await autozoomCtl.updateOpts({
                shouldAutoFrame: false,
            })
        }
    });
}

init();
```
And will update when the workaround is no longer necessary.

**Comment by qmas** [comment] 2019-11-05 17:58
Thanks. Yes people count is fine when the following requirements are met:
1. Sdk is 0.4.0 
2. HuddlyIQ  1.3.13 
3. plus suggested workaround 
4: DOWS:true, az=true or az=false

You may close this issue for now. I guess I can create new issue if needed.

**Closed** 2019-12-06 09:39 UTC
Labels: bug
