### ISSUE TITLE
No DETECTION running sample code

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#35] opened 2019-01-18 16:23 UTC
I get no DETECTION running sample code
C:\tmp\sdk-master\sdk-master\examples\ga_peoplecount>node ga_peoplecount.js
:::::::::::: Transport Protocol is HLINK ::::::::::::
logger.js:13
Start cnn enable

Two lines of code were changed:
1. Sample code will run not without aysnc
    sdk.on('ATTACH', async (cameraManager) => {
2. Adding { convertDetections: 'FRAMING' } did not make any difference 
      const detector = cameraManager.getDetector({ convertDetections: 'FRAMING' } );

Platform is Windows 10 Pro, Node v8.9.0 , npm 5.6.0

**Comment by qmas** [comment] 2019-01-21 15:49
additional information for this issue:
Camera Information: 
<pre>serialNumber    =  B40J00080
version         =  1.0.3-29761
softwareVersion =  HuddlyIQ-1.0.3-29761</pre>

Camera displays video in Skype for Business Settings during the test.

**Comment by jontore** [comment] 2019-01-21 15:50
Hi @qmas , thank you for your feedback, and pointing out the bugs in the example sorry for that.

There was introduced a regression for older camera sw it the lastest release, thank you for pointing that out. It should be fixed in new  0.1.7 release. 

Other than that.
Make sure you do not have the huddly app running, since the sdk is used by the app it will try to require the same USB endpoint.

For now you have to start streaming from the camera for detections to work, so that means you have to open a video application for instance the camera app on widows,  and select Huddly IQ. You should then start seeing detections coming in. 

Hopefully this will be unnecessary soon. 

Cheers

**Comment by qmas** [comment] 2019-01-21 16:21
I am having issue with running sample code from Huddly/sdk. Please see the code snippet bellow. I expect the log line "Number of people detected" logged every time someone walks in the view of camera. This log message is never reached. Whats an issue here? 
  
```
sdk.on('ATTACH', async (cameraManager) => {
      const detector = cameraManager.getDetector({ convertDetections: 'FRAMING' } );
      await detector.init();
    
      detector.on('DETECTIONS', (detections) => {
        console.log('Number of people detected', detections.length);
      });

      detector.start();
    });
```

**Comment by qmas** [comment] 2019-01-21 16:31
I tried two different video applications: Skyp for Business and Windows 10 Camera app. Repeating camera information
```
serialNumber    =  B40J00080
version         =  1.0.3-29761
softwareVersion =  HuddlyIQ-1.0.3-29761 
```

**Comment by jontore** [comment] 2019-01-21 16:41
Sorry about that, 

Right so that should work with the patch I released to today can you verify that you have the correct version of the sdk in the ```node_modules``` folder in the ```ga_peoplecount``` folder. run ```cat node_modules/@huddly/sdk/package.json```

**Comment by qmas** [comment] 2019-01-21 16:53
cat did not work for me on Widows, tried npm list. Let me know if its not write I can attach file with versions of all the modules   
```
npm list  node_modules/@huddly/sdk/package.json
huddlyInfo@1.0.0 C:\tmp\nodejs\HuddlyCount
`-- (empty)
```

**Comment by jontore** [comment] 2019-01-21 16:55
```npm list``` is great could you include the whole output from the command

**Comment by qmas** [comment] 2019-01-21 16:57
Ok. File is attached 
[npm_list.txt](https://github.com/Huddly/sdk/files/2779821/npm_list.txt)

**Comment by jontore** [comment] 2019-01-21 17:00
Right you're running version ```+-- @huddly/sdk@0.1.5``` remove your ```node_modules``` folder and/or package-lock.json file, and run ```npm i``` again. Then you can run ```npm list ``` to verify that it is version ```+-- @huddly/sdk@0.1.7```

**Comment by qmas** [comment] 2019-01-21 17:24
Thank your very much. This seems to be working.The current npm list file is attached. 
[npm_list_2.txt](https://github.com/Huddly/sdk/files/2779898/npm_list_2.txt)

I noticed at one point there were 2 people in the view and it logged 3. besides this one time people count was accurate.

**Comment by jontore** [comment] 2019-01-21 17:39
Great 👍 thank you for filing the bug.

**Closed by jontore** 2019-01-21 17:39 UTC
